### ISSUE TITLE
Requiring openssl before fast-rsa-engine throws a LoadError

### ISSUE THREAD

**Issue by PeterFCaswell** [lookout/fast-rsa-engine#14]
Under JRuby 1.7.21, this program:

```
#!/usr/bin/env ruby

puts('')
puts("_____ Test Case  _____")

require 'openssl'
require 'fast-rsa-engine'

puts("      Ruby   v#{RUBY_VERSION}")
puts('It worked')
```

Yields a LoadError:
```

_____ Test Case  _____
openssl loaded before fast-rsa-engine
LoadError: load error: fast-rsa-engine -- java.lang.ClassNotFoundException: com.github.lookout.fastrsa.FastDigestSignatureSpi$MD2
  require at org/jruby/RubyKernel.java:1040
   (root) at bin/simple-test:7
```
This is using fast-rsa-engine 0.2.1
```
; bundle show fast-rsa-engine
/Users/pcaswell/.rvm/gems/jruby-1.7.21/gems/fast-rsa-engine-0.2.1-java
```

**Comment by rtyler** [comment]
The nice thing about an exception, is that the user has to fix the error :package: 

The bad thing about the exception, is that it *might* not be possible for the user to fix the error.


I'll have to ponder more on this, @mkristian do you have a strong opinion on the behavior here?

**Comment by mkristian** [comment]
I would go with a warning as it allows to use regular RSA as in MRI or old jossl-gem, etc
