### ISSUE TITLE
fast-rsa-engine for JRuby 1.7.19 puts out a context-free warning

### ISSUE THREAD

**Issue by PeterFCaswell** [lookout/fast-rsa-engine#15]
If I run with the fast-rsa-engine under JRuby 1.7.19, I see this message:
```
jruby-openssl gem 0.9.5 is too old
```

It would be nice if this error message indicated that it was coming from the fast-rsa-engine, otherwise, people are likely to scratch their heads when they see it.

**Comment by mkristian** [comment]
I see - right
