### ISSUE TITLE
NixOS: libgmp fails to load due to UnsatisfiedLinkError

### ISSUE THREAD

**Issue by crufia** [lookout/fast-rsa-engine#19]
When using fast-rsa in the nixos environment, I can't load gmp unless I specify the .so lib path explicitly in jna.library.path. Here's the stacktrace I see:

Java::JavaLang::UnsatisfiedLinkError (Unable to load library 'gmp': Native library (linux-x86-64/libgmp.so) not found in resource path ([file:/tmp/jetty-0.0.0.0-8080-<lol>.dir/webapp/WEB-INF/lib/jruby-core-1.7.22.jar, file:/tmp/jetty-0.0.0.0-8080-<lol>.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.22.jar, file:/tmp/jetty-0.0.0.0-8080-<lol>.dir/webapp/WEB-INF/lib/<trolol>.null.jar, file:/tmp/jetty-0.0.0.0-8080-<lol>.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar])):
  com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
  com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
  com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:337)
  com.squareup.jnagmp.LibGmp.load(LibGmp.java:69)
  com.squareup.jnagmp.LibGmp.loadLibGmp(LibGmp.java:65)
  com.squareup.jnagmp.LibGmp.<clinit>(LibGmp.java:52)
  com.squareup.jnagmp.GmpInteger$MpzMemory.<init>(GmpInteger.java:40)
  com.squareup.jnagmp.GmpInteger.<init>(GmpInteger.java:49)
  com.squareup.crypto.rsa.NativeRSACoreEngine.init(NativeRSACoreEngine.java:71)
  com.squareup.crypto.rsa.NativeRSAEngine.init(NativeRSAEngine.java:34)
  org.bouncycastle.crypto.encodings.PKCS1Encoding.init(Unknown Source)
  org.bouncycastle.jcajce.provider.asymmetric.rsa.DigestSignatureSpi.engineInitSign(Unknown Source)
  java.security.Signature$Delegate.engineInitSign(Signature.java:1174)
  java.security.Signature.initSign(Signature.java:527)
  org.jruby.ext.openssl.PKey.sign(PKey.java:207)
etc...

**Comment by mkristian** [comment]
this looks very much like a warbler war file :)

what is the file:/tmp/jetty-0.0.0.0-8080-.dir/webapp/WEB-INF/lib/.null.jar
? not sure if this is something jetty just adds. assume it warbled war-file
has it as well

before I start digging into warbler I would appreciate more info how you
created the warfile or some minimal sample project.

**Comment by rtyler** [comment]
@crufia Out of curiosity, what is the explicit `jna.library.path` you did set to make this work? 

@mkristian My first thinking when I saw this issue was that it might be something that jnr/jnr-ffi#50 might solve, since NixOS (a Debian-derivative) does a lot of clever tricks to ensure isolation and immutability, and futzing with the load paths might be one of them

**Comment by mkristian** [comment]
@rtyler not sure since the linux-x86-64/libgmp.so is part of transitive jar from the gem

there is some other load issue here.

but yes, it would be nice to add this jnr-ffi jar to war but that is not possible with jnr-ffi :(

**Comment by crufia** [comment]
Thanks guys. I'll ping you privately about warbler and how I create the war file - fwiw, I made a mistake when formatting the issue. I didn't realize that angle brackets would disappear entirely. I had a bunch of (lol)s here, except, well...

**Comment by mkristian** [comment]
the load library code looks into the wrong classloader. workaround for the current gem:

```
java.lang.Thread.currentThread.context_class_loader = JRuby.runtime.jruby_class_loader
```

**Comment by crufia** [comment]
I confirmed that the issue is isolated to warbler (or at least has nothing to do with nix). The workaround (specifying the classloader before requiring fast-rsa-engine) didn't work - same issue.

**Comment by mkristian** [comment]
that is what I feared that the classloader change does not stick.

```diff
diff --git a/config/application.rb b/config/application.rb
index 9fe070d..673bc94 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -41,3 +41,9 @@ module MyApp
   end
 end
+
+java.lang.Thread.currentThread.context_class_loader = JRuby.runtime.jruby_class_loader
+
+require 'fast-rsa-engine'
+private_key = OpenSSL::PKey::RSA.new(File.read(File.expand_path('../foo.pem', __FILE__)))
+p private_key.sign(OpenSSL::Digest.new('sha512'), 'hello world')
```

where I immediately load the native library by using the respective code.

**Comment by mkristian** [comment]
will prepare a workaround for the gem but want to wait for a feedback from square/jna-gmp

**Comment by mkristian** [comment]
@crufia this is the hack I prepared. https://github.com/lookout/fast-rsa-engine/commit/d5e8e127b6e4e923e1a1b26100e0ca8c9861c874

could you try it on your side if this helps to make sure it works if I release a new gem

**Comment by mkristian** [comment]
the actual fix would be a new release with: https://github.com/square/jna-gmp/pull/4
