### ISSUE TITLE
If we can't load the jars for whatever reason, that should not be a fatal error

### ISSUE THREAD

**Issue by rtyler** [lookout/fast-rsa-engine#22]
Lots of projects that have, let's call them "dysfunctional" build systems which aren't properly installing jars via [JRuby/Gradle](http://jruby-gradle.org) or [jbundler](https://github.com/mkristian/jbundler) will end up with runtime errors, e.g.:

```
2015-09-11 15:19:07 rake aborted!
2015-09-11 15:19:07 
2015-09-11 15:19:07 
2015-09-11 15:19:07 	you might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command
2015-09-11 15:19:07 
2015-09-11 15:19:07 no such file to load -- com/squareup/jnagmp/bouncycastle-rsa/1.0.0/bouncycastle-rsa-1.0.0 (LoadError)
```

I do not believe this should be a critical error, but that we should act the same as on MRI, i.e. no-op.

**Comment by mkristian** [comment]
is this happening how ? installing via MRI and then using with JRuby ? yes, the latter indeed has this corrupted _jars.rb file. that can be fixed - but maybe a platform java only gem would be the better way to go ?

**Comment by rtyler** [comment]
The project in question was using JRuby but had no previous jar-based dependencies whatsoever and therefore had nothing like jbundler to resolve dependencies. Without *something* executing to install the jar dependencies this will fail won't it? A couple of scenarios that come to mind:

 * no JRuby/Gradle
 * no jbundler
 * jar-dependencies 0.1.x in the lock file
 * no maven present

These can all result in this failure no?

**Comment by mkristian** [comment]
jar-dependencies is default gem with jruby since version 1.7.18 (or 1.7.17 or earlier). jar-dependencies will install ruby-maven if not installed. in the next jruby release there will be no ruby-maven preinstalled anymore so this is the standard case.

jbundler or jruby-gradle will help as well.

with older jrubies there is no way to get it working with bundler. jar-dependencies in Gemfile will not help here either, it needs the rubygems post-install hook, rubygems does work with older jrubies if jar-dependencies is already install:

```
gem install jar-dependencies
gem install fast-rsa-engine
```
will work with all jrubies (fresh install). with newer jrubies either way works
```
gem install fast-rsa-engine
```
or just add ```gem 'fast-rsa-engine'``` to your Gemfile and run
```
bundle install
```

all cases do not need ruby-maven installed before hand. that is more or less how travis tests the gem - and it does not install ruby-maven through Gemfile ! just tried this with jruby-1.7.17 and it works (for me).

can it be that this was an older jruby ?

**Comment by rtyler** [comment]
IIRC this was with JRuby 1.7.21, later today (still running errands) I'll jump onto VPN and check out the specifics of the project and make a small reproduction case.

**Comment by mkristian** [comment]
thanx, very much appreciated

**Comment by rtyler** [comment]
Here's a reproduction case:

* `rvm use jruby-1.7.20`
* `gem install fast-rsa-engine -N`
* `ruby -e "require 'fast-rsa-engine'"`


Which will dump:

```
RuntimeError: 

	you might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command

no such file to load -- com/squareup/jnagmp/bouncycastle-rsa/1.0.0/bouncycastle-rsa-1.0.0 (LoadError)
              do_require at /home/ubuntu/.rvm/gems/jruby-1.7.20@rubygems/gems/jar-dependencies-0.2.1/lib/jar_dependencies.rb:309
             require_jar at /home/ubuntu/.rvm/gems/jruby-1.7.20@rubygems/gems/jar-dependencies-0.2.1/lib/jar_dependencies.rb:228
  require_jar_with_block at /home/ubuntu/.rvm/gems/jruby-1.7.20@rubygems/gems/jar-dependencies-0.2.1/lib/jar_dependencies.rb:0
             require_jar at /home/ubuntu/.rvm/gems/jruby-1.7.20@rubygems/gems/jar-dependencies-0.2.1/lib/jar_dependencies.rb:227
             require_jar at /home/ubuntu/.rvm/gems/jruby-1.7.20@rubygems/gems/jar-dependencies-0.2.1/lib/jar_dependencies.rb:318
                  (root) at /home/ubuntu/.rvm/gems/jruby-1.7.20@rubygems/gems/fast-rsa-engine-0.3.1-java/lib/fast-rsa-engine_jars.rb:4
                 require at org/jruby/RubyKernel.java:1072
                  (root) at /home/ubuntu/.rvm/rubies/jruby-1.7.20/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
                 require at /home/ubuntu/.rvm/rubies/jruby-1.7.20/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:69
                 require at org/jruby/RubyKernel.java:1072
                  (root) at /home/ubuntu/.rvm/gems/jruby-1.7.20@rubygems/gems/fast-rsa-engine-0.3.1-java/lib/fast-rsa-engine.rb:2
                  (root) at -e:1
```
