### ISSUE TITLE
Allow including gem as a no-op dependency in MRI

### ISSUE THREAD

**Issue by rtyler** [lookout/fast-rsa-engine#7]
This is basically what #4 is about, but I wanted to create this issue to track the requirement.

Basically by making the gem a no-op dependency on MRI, we'll be able to default it as a transitive dependency in a *lot* of places until this code is merged up with jruby-opensll

**Comment by mkristian** [comment]
fixed via #4 and 112bd95ec0f96bc18d449d58ee6a57300bbdc1af
